### ISSUE TITLE
Windshaft

### ISSUE THREAD

**Issue by evanzummeren** [HDAT/HDAT#16]
git clone https://github.com/CartoDB/Windshaft.git

brew install mapnik --with-cairo --with-gdal --with-postgresql
[Ik kreeg een melding dat ik xquartz moest installeren, dat heb ik gedaan
en daarna deed hij het]

brew install https://gist.githubusercontent.com/evanzummeren/7d687934074288092451/raw/a4c2f461a34ae28aae335fbdf9fe3ae23b686fe1/imagemagick.rb

npm install

PGUSER=root npm test

**Comment by evanzummeren** [comment]
Oke, ik ben weer ouderwets errors aan het oplossen. 267 passing 5 pending 6 failing....

**Comment by evanzummeren** [comment]
Ik ga hier later verder mee. Heb nu de volgende fouten:
```
  1) render_cache can generate a tilelive object:
     Uncaught TypeError: Cannot call method 'get' of undefined
      at EventEmitter.CacheEntry.get (/Users/erik/Desktop/Windshaft/lib/windshaft/cache/cache_entry.js:34:26)
      at /Users/erik/Desktop/Windshaft/test/unit/render_cache.test.js:106:32
      at EventEmitter.CacheEntry.setReady (/Users/erik/Desktop/Windshaft/lib/windshaft/cache/cache_entry.js:49:9)
      at /Users/erik/Desktop/Windshaft/lib/windshaft/renderers/render_cache.js:114:37
      at Function.returnCallback (/Users/erik/Desktop/Windshaft/lib/windshaft/renderers/renderer_factory.js:112:20)
      at next (/Users/erik/Desktop/Windshaft/node_modules/step/lib/step.js:51:23)
      at next (/Users/erik/Desktop/Windshaft/node_modules/step/lib/step.js:54:7)
      at Function.returnCallback (/Users/erik/Desktop/Windshaft/lib/windshaft/renderers/mapnik/factory.js:115:13)
      at MapnikSource.next (/Users/erik/Desktop/Windshaft/node_modules/step/lib/step.js:51:23)
      at MapnikSource.g (events.js:180:16)
      at MapnikSource.emit (events.js:95:17)
      at /Users/erik/Desktop/Windshaft/node_modules/tilelive-mapnik/lib/mapnik_backend.js:129:20
      at process._tickCallback (node.js:419:13)

  2) render_cache can generate > 1 tilelive object:
     Uncaught AssertionError: 1 == 2
      at /Users/erik/Desktop/Windshaft/test/unit/render_cache.test.js:128:24
      at EventEmitter.CacheEntry.setReady (/Users/erik/Desktop/Windshaft/lib/windshaft/cache/cache_entry.js:49:9)
      at /Users/erik/Desktop/Windshaft/lib/windshaft/renderers/render_cache.js:114:37
      at Function.returnCallback (/Users/erik/Desktop/Windshaft/lib/windshaft/renderers/renderer_factory.js:112:20)
      at next (/Users/erik/Desktop/Windshaft/node_modules/step/lib/step.js:51:23)
      at next (/Users/erik/Desktop/Windshaft/node_modules/step/lib/step.js:54:7)
      at Function.returnCallback (/Users/erik/Desktop/Windshaft/lib/windshaft/renderers/mapnik/factory.js:115:13)
      at MapnikSource.next (/Users/erik/Desktop/Windshaft/node_modules/step/lib/step.js:51:23)
      at MapnikSource.g (events.js:180:16)
      at MapnikSource.emit (events.js:95:17)
      at /Users/erik/Desktop/Windshaft/node_modules/tilelive-mapnik/lib/mapnik_backend.js:129:20
      at process._tickCallback (node.js:419:13)

  3) render_cache can delete all tilelive objects when reset:
     Uncaught AssertionError: 1 == 2
      at /Users/erik/Desktop/Windshaft/test/unit/render_cache.test.js:165:24
      at EventEmitter.CacheEntry.setReady (/Users/erik/Desktop/Windshaft/lib/windshaft/cache/cache_entry.js:49:9)
      at /Users/erik/Desktop/Windshaft/lib/windshaft/renderers/render_cache.js:114:37
      at Function.returnCallback (/Users/erik/Desktop/Windshaft/lib/windshaft/renderers/renderer_factory.js:112:20)
      at next (/Users/erik/Desktop/Windshaft/node_modules/step/lib/step.js:51:23)
      at next (/Users/erik/Desktop/Windshaft/node_modules/step/lib/step.js:54:7)
      at Function.returnCallback (/Users/erik/Desktop/Windshaft/lib/windshaft/renderers/mapnik/factory.js:115:13)
      at MapnikSource.next (/Users/erik/Desktop/Windshaft/node_modules/step/lib/step.js:51:23)
      at MapnikSource.g (events.js:180:16)
      at MapnikSource.emit (events.js:95:17)
      at /Users/erik/Desktop/Windshaft/node_modules/tilelive-mapnik/lib/mapnik_backend.js:129:20
      at process._tickCallback (node.js:419:13)

  4) render_cache can delete only related tilelive objects when reset:
     Uncaught AssertionError: 1 == 3
      at /Users/erik/Desktop/Windshaft/test/unit/render_cache.test.js:189:28
      at EventEmitter.CacheEntry.setReady (/Users/erik/Desktop/Windshaft/lib/windshaft/cache/cache_entry.js:49:9)
      at /Users/erik/Desktop/Windshaft/lib/windshaft/renderers/render_cache.js:114:37
      at Function.returnCallback (/Users/erik/Desktop/Windshaft/lib/windshaft/renderers/renderer_factory.js:112:20)
      at next (/Users/erik/Desktop/Windshaft/node_modules/step/lib/step.js:51:23)
      at next (/Users/erik/Desktop/Windshaft/node_modules/step/lib/step.js:54:7)
      at Function.returnCallback (/Users/erik/Desktop/Windshaft/lib/windshaft/renderers/mapnik/factory.js:115:13)
      at MapnikSource.next (/Users/erik/Desktop/Windshaft/node_modules/step/lib/step.js:51:23)
      at MapnikSource.g (events.js:180:16)
      at MapnikSource.emit (events.js:95:17)
      at /Users/erik/Desktop/Windshaft/node_modules/tilelive-mapnik/lib/mapnik_backend.js:129:20
      at process._tickCallback (node.js:419:13)

  5) render_cache clears both auth and non-auth renderer caches on reset:
     Uncaught AssertionError: 2 == 3
      at /Users/erik/Desktop/Windshaft/test/unit/render_cache.test.js:221:28
      at EventEmitter.CacheEntry.setReady (/Users/erik/Desktop/Windshaft/lib/windshaft/cache/cache_entry.js:49:9)
      at /Users/erik/Desktop/Windshaft/lib/windshaft/renderers/render_cache.js:114:37
      at Function.returnCallback (/Users/erik/Desktop/Windshaft/lib/windshaft/renderers/renderer_factory.js:112:20)
      at next (/Users/erik/Desktop/Windshaft/node_modules/step/lib/step.js:51:23)
      at next (/Users/erik/Desktop/Windshaft/node_modules/step/lib/step.js:54:7)
      at Function.returnCallback (/Users/erik/Desktop/Windshaft/lib/windshaft/renderers/mapnik/factory.js:115:13)
      at MapnikSource.next (/Users/erik/Desktop/Windshaft/node_modules/step/lib/step.js:51:23)
      at MapnikSource.g (events.js:180:16)
      at MapnikSource.emit (events.js:95:17)
      at /Users/erik/Desktop/Windshaft/node_modules/tilelive-mapnik/lib/mapnik_backend.js:129:20
      at process._tickCallback (node.js:419:13)

  6) render_cache can purge all tilelive objects:
     Uncaught AssertionError: 1 == 3
      at /Users/erik/Desktop/Windshaft/test/unit/render_cache.test.js:251:28
      at EventEmitter.CacheEntry.setReady (/Users/erik/Desktop/Windshaft/lib/windshaft/cache/cache_entry.js:49:9)
      at /Users/erik/Desktop/Windshaft/lib/windshaft/renderers/render_cache.js:114:37
      at Function.returnCallback (/Users/erik/Desktop/Windshaft/lib/windshaft/renderers/renderer_factory.js:112:20)
      at next (/Users/erik/Desktop/Windshaft/node_modules/step/lib/step.js:51:23)
      at next (/Users/erik/Desktop/Windshaft/node_modules/step/lib/step.js:54:7)
      at Function.returnCallback (/Users/erik/Desktop/Windshaft/lib/windshaft/renderers/mapnik/factory.js:115:13)
      at MapnikSource.next (/Users/erik/Desktop/Windshaft/node_modules/step/lib/step.js:51:23)
      at MapnikSource.g (events.js:180:16)
      at MapnikSource.emit (events.js:95:17)
      at /Users/erik/Desktop/Windshaft/node_modules/tilelive-mapnik/lib/mapnik_backend.js:129:20
      at process._tickCallback (node.js:419:13)
```

**Comment by evanzummeren** [comment]
Ok, dat was nog wel te doen. Ik moest er een user bijmaken.

Binnen psql:
CREATE USER postgres WITH PASSWORD '';
GRANT ALL PRIVILEGES ON DATABASE "template_postgis" to postgres;

Hij doorstaat de test, maar heeft er nog wel 5 pending. Maar ik denk niet dat die noodzakelijk zijn voor torque. Dus alles bij elkaar:

```
git clone https://github.com/CartoDB/Windshaft.git

brew install mapnik --with-cairo --with-gdal --with-postgresql
[Ik kreeg een melding dat ik xquartz moest installeren, dat heb ik gedaan
en daarna deed hij het]

brew install https://gist.githubusercontent.com/evanzummeren/7d687934074288092451/raw/a4c2f461a34ae28aae335fbdf9fe3ae23b686fe1/imagemagick.rb

npm install

psql > CREATE USER postgres WITH PASSWORD '';
psql > GRANT ALL PRIVILEGES ON DATABASE "template_postgis" to postgres;
psql > \q

PGUSER=root npm test
```
